const configureSvgIcon = require('react-svg-icon');
const path = require('path');

configureSvgIcon({
  comment: 'Generated by gulp svg-icon, if you add new icon run gulp svg-icon', //optional
  //svgDir: path.join(__dirname, 'icons'),
  svgDir: './icons',
  //template: path.join('template', 'icon.nunjucks'),
  reactPureRender: false,
  destination: path.join(__dirname, 'components', 'Icon.js'),
});
