import minifySvg from './helpers/minifySvg';
import nunjucks from 'nunjucks';
import Promise from 'bluebird';
import templateContent from '../template/icon.nunjucks';
import {cleanupName, cleanupSvg} from './helpers/cleanup';

nunjucks.configure({ autoescape: false });

const defaultComment = 'Generated by gulp svg-icon - do not modify manually';

function readFile(file) {
  return new Promise(resolve => {
    const reader = new FileReader();
    reader.onload = (e) => resolve({file: file.name, content: e.target.result});
    reader.readAsDataURL(file);
  });
}

export default function generateInline(config, svgFiles) {
  const comment = config.comment || defaultComment;
  const reactPureRender = config.reactPureRender;

  const fileReaders = svgFiles.map(file => readFile(file));

  return Promise.all(fileReaders).then(svgs => {
    const svgPromises = svgs.map(file => minifySvg(file.name, file.content));

    return Promise.all(svgPromises).then(results => {
      const icons = results.map(result => {
        return {
          name: cleanupName(result.name),
          svg: cleanupSvg(result.svg.data)
        };
      }).sort((a, b) => a.name.localeCompare(b.name));

      return nunjucks.renderString(templateContent, {icons, comment, reactPureRender});
    });
  });
}
